// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTaDfjNVxDgM82AAq9jgVYOjtiQ4CV7Y',
    appId: '1:792812168466:web:dcf95a973c0dd78e8e7fcb',
    messagingSenderId: '792812168466',
    projectId: 'tracking-app-5aafd',
    authDomain: 'tracking-app-5aafd.firebaseapp.com',
    databaseURL: 'https://tracking-app-5aafd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tracking-app-5aafd.appspot.com',
    measurementId: 'G-ZENM2BH3ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOl6xuwuvPflx8KMaZ8VuJg6g-5gO-Xh0',
    appId: '1:792812168466:android:b67bb60f93d08bb68e7fcb',
    messagingSenderId: '792812168466',
    projectId: 'tracking-app-5aafd',
    databaseURL: 'https://tracking-app-5aafd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tracking-app-5aafd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnZDD92riqz29TFnMDB7uPfkdaf2TxNE',
    appId: '1:792812168466:ios:45edd9afa9274c4d8e7fcb',
    messagingSenderId: '792812168466',
    projectId: 'tracking-app-5aafd',
    databaseURL: 'https://tracking-app-5aafd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tracking-app-5aafd.appspot.com',
    iosClientId: '792812168466-eif73kkpfi1ul6pbtm7viks3ttkvc9k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingApp',
  );
}